from app.controllers.farmer.farmer_login_controller import farmer_login_control
from app.controllers.farmer.validate_farmer import farmer_validate
from app.controllers.farmer.Registerfarmer import farmer_reg_bp
from app.controllers.farmer.farmer_reset_password import farmer_reset_password_bp
from app.controllers.farmer.farmer_dashboard import farmer_dashboard_bp
from app.controllers.payment_gateway import payment_gateway_method
from app.controllers.farmer.cattle_section import add_cattle, display_cattle
from app.controllers.farmer.farmer_milk_history import farmer_milk_transaction_bp
from app.controllers.farmer.farmer_product import farmer_product_bp
from app.controllers.farmer.farmer_add_address import add_delivery_address
from app.controllers.farmer.farmer_cart import view_cart